// <auto-generated />
using System;
using Garage_2_0.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace garage_2._0.Migrations
{
    [DbContext(typeof(GarageDbContext))]
    [Migration("20240422175125_ParkingSpotVehicleManyToMany")]
    partial class ParkingSpotVehicleManyToMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Garage_2_0.Models.Garage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParkingSpotCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Garages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Default Garage 1",
                            ParkingSpotCount = 5
                        },
                        new
                        {
                            Id = 2,
                            Name = "Default Garage 2",
                            ParkingSpotCount = 5
                        });
                });

            modelBuilder.Entity("Garage_2_0.Models.ParkingSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContainsVehicleType")
                        .HasColumnType("int");

                    b.Property<int>("GarageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GarageId");

                    b.ToTable("ParkingSpots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContainsVehicleType = 0,
                            GarageId = 1
                        },
                        new
                        {
                            Id = 2,
                            ContainsVehicleType = 0,
                            GarageId = 1
                        },
                        new
                        {
                            Id = 3,
                            ContainsVehicleType = 0,
                            GarageId = 1
                        },
                        new
                        {
                            Id = 4,
                            ContainsVehicleType = 0,
                            GarageId = 1
                        },
                        new
                        {
                            Id = 5,
                            ContainsVehicleType = 0,
                            GarageId = 1
                        },
                        new
                        {
                            Id = 6,
                            GarageId = 2
                        },
                        new
                        {
                            Id = 7,
                            GarageId = 2
                        },
                        new
                        {
                            Id = 8,
                            GarageId = 2
                        },
                        new
                        {
                            Id = 9,
                            GarageId = 2
                        },
                        new
                        {
                            Id = 10,
                            GarageId = 2
                        });
                });

            modelBuilder.Entity("Garage_2_0.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("GarageId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 22, 19, 51, 24, 495, DateTimeKind.Local).AddTicks(2844));

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Wheels")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Volkswagen",
                            Color = 4,
                            GarageId = 1,
                            Model = "Unknown",
                            RegisteredAt = new DateTime(2024, 4, 22, 19, 51, 24, 495, DateTimeKind.Local).AddTicks(4161),
                            RegistrationNumber = "FPD941",
                            Type = 0,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Saab",
                            Color = 1,
                            GarageId = 1,
                            Model = "Unknown",
                            RegisteredAt = new DateTime(2024, 4, 22, 19, 51, 24, 495, DateTimeKind.Local).AddTicks(4176),
                            RegistrationNumber = "CLQ415",
                            Type = 0,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Volvo",
                            Color = 2,
                            GarageId = 1,
                            Model = "Unknown",
                            RegisteredAt = new DateTime(2024, 4, 22, 19, 51, 24, 495, DateTimeKind.Local).AddTicks(4179),
                            RegistrationNumber = "YHV901",
                            Type = 0,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Audi",
                            Color = 7,
                            GarageId = 1,
                            Model = "Unknown",
                            RegisteredAt = new DateTime(2024, 4, 22, 19, 51, 24, 495, DateTimeKind.Local).AddTicks(4181),
                            RegistrationNumber = "GBO781",
                            Type = 0,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Toyota",
                            Color = 0,
                            GarageId = 1,
                            Model = "Unknown",
                            RegisteredAt = new DateTime(2024, 4, 22, 19, 51, 24, 495, DateTimeKind.Local).AddTicks(4184),
                            RegistrationNumber = "JRC132",
                            Type = 0,
                            Wheels = 4
                        });
                });

            modelBuilder.Entity("ParkingSpotVehicle", b =>
                {
                    b.Property<int>("ParkingSpotsId")
                        .HasColumnType("int");

                    b.Property<int>("VehiclesId")
                        .HasColumnType("int");

                    b.HasKey("ParkingSpotsId", "VehiclesId");

                    b.HasIndex("VehiclesId");

                    b.ToTable("ParkingSpotVehicle");

                    b.HasData(
                        new
                        {
                            ParkingSpotsId = 1,
                            VehiclesId = 1
                        },
                        new
                        {
                            ParkingSpotsId = 2,
                            VehiclesId = 2
                        },
                        new
                        {
                            ParkingSpotsId = 3,
                            VehiclesId = 3
                        },
                        new
                        {
                            ParkingSpotsId = 4,
                            VehiclesId = 4
                        },
                        new
                        {
                            ParkingSpotsId = 5,
                            VehiclesId = 5
                        });
                });

            modelBuilder.Entity("Garage_2_0.Models.ParkingSpot", b =>
                {
                    b.HasOne("Garage_2_0.Models.Garage", "Garage")
                        .WithMany("ParkingSpots")
                        .HasForeignKey("GarageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garage");
                });

            modelBuilder.Entity("ParkingSpotVehicle", b =>
                {
                    b.HasOne("Garage_2_0.Models.ParkingSpot", null)
                        .WithMany()
                        .HasForeignKey("ParkingSpotsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Garage_2_0.Models.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehiclesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Garage_2_0.Models.Garage", b =>
                {
                    b.Navigation("ParkingSpots");
                });
#pragma warning restore 612, 618
        }
    }
}
